<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo Mage::getUrl('arithmetic/integer/multiply') ?>" method="post">
	<fieldset>
		<ul>
			<li>
				<label for="int1">Integer 1</label>
				<input type="text" id="int1" name="int1" />
			</li>
			<li>
				<label for="int2">Integer 2</label>
				<input type="text" id="int2" name="int2" />
			</li>
			<li>
				<input type="submit" value="Multiply" />
			</li>
		</ul>
	</fieldset>
</form>